---
kind: pipeline
type: docker
name: build-test

platform:
  os: linux
  arch: amd64

steps:
- name: build-modules
  image: golang:1.16.2-stretch
  commands:
  - go mod tidy
  - go build -v ./...
  - go mod vendor
  volumes:
  - name: deps
    path: /go

- name: wait-for-it
  pull: always
  image: svajone/wait-for-it:latest
  commands:
  - apk add --update --no-cache bash
  - "wait-for-it.sh -h 'postgres' -p 5432 -t 180"

- name: postgres-migrations
  pull: always
  image: svajone/pgmngr:v0.1.0
  commands:
  - pgmngr -c .pgmngr.json migration forward
  depends_on:
  - wait-for-it

- name: test
  image: golang:1.16.2-stretch
  commands:
  - tests/scripts/testcov.sh
  environment:
    DBAL_PG_DB: "postgres://dbal:dbal@postgres:5432/dbal_development?sslmode=disable"
  volumes:
  - name: deps
    path: /go
  depends_on:
  - build-modules
  - postgres-migrations

- name: codecov
  image: plugins/codecov
  settings:
    paths:
    - .cover
    required: true
    token:
      from_secret: codecov-token
  volumes:
  - name: deps
    path: /go
  depends_on:
  - test

services:
- name: postgres
  image: postgres:11
  environment:
    POSTGRES_DB: dbal_development
    POSTGRES_PASSWORD: dbal
    POSTGRES_USER: dbal

volumes:
- name: deps
  temp: {}
